content = open('env.py', 'r', encoding='utf-8').read()
content = content.replace('idle_penalty_scaler = 10.0', 'idle_penalty_scaler = 2.0')
content = content.replace('(rejected_dl * 10.0)', '(rejected_dl * 2.0)')
content = content.replace('(rejected_cf * 2.5)', '(rejected_cf * 0.5)')
content = content.replace('(rejected_coflows * 2.5)', '(rejected_coflows * 0.5)')
content = content.replace('drop_penalty = len(flows_to_drop) * 10.0', 'drop_penalty = len(flows_to_drop) * 2.0')
content = content.replace('congestion_penalty = 10.0 * (mlu - 0.8) ** 2', 'congestion_penalty = 2.0 * (mlu - 0.8) ** 2')
content = content.replace('(completed_dl * 5.0) + (completed_cf * 2.0) + (completed_bk * 0.5)', '(completed_dl * 1.5) + (completed_cf * 0.5) + (completed_bk * 0.1)')
open('env.py', 'w', encoding='utf-8').write(content)
